server:
  port: 8080

app:
  brevify:
    baseUrl: http://localhost:8080/

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/brevify
    username: kamal
    password: N3@K2gVoHb76
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-migration-naming: true
  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "brevify-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    host: localhost
    port: 6379
    timeout: 60000

jwt:
  secret: 8a891892da4b9a8540dc452a97a9f9de9c1042578032a5aca3caa3d8acc81229ed0eac3b32096e60e1a967ecb9531b3766766af35729d1c7e0ec1f307b3da1fa35b2c487965c948ef9f6e9256cbea71943a998d53649abaed77d7afb1b525e513564afe57a73b157395733ba9d7406a68f1e6f38bc1da1963625b086890c62acfac8faf5ceab9a100e199dfc9b91307160dd4cf70913d493bff5ccc72622ba7c7156837f0849e5df83811a7b75134466808b7b085a5c2045aa333def98b0523f4fca5f8d0e69234d9f57469000cf907446d7bee7c7292f96f6ae444368d6a4a009850a9048cb9ec67f86589762e48e710444239913c6a8fa497c0c2f42fdfaf6
  expiration: 3600

logging:
  level:
    root: INFO